; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using the MEGA Prototyper.
[ MEGAinfo ]
ver=0
[ DataSettings ]
datatype=snNucleotide
containsCodingNuc=False
missingBaseSymbol=?
identicalBaseSymbol=.
gapSymbol=-
[ ProcessTypes ]
ppInfer=true
ppNJ=true
[ AnalysisSettings ]
Analysis=Phylogeny Reconstruction
Scope=All Selected Taxa
Statistical Method=Neighbor-joining
Phylogeny Test=====================
Test of Phylogeny=Bootstrap method
No. of Bootstrap Replications=1000
Substitution Model=====================
Substitutions Type=Nucleotide
Model/Method=p-distance
Substitutions to Include=d: Transitions + Transversions
Rates and Patterns=====================
Rates among Sites=Uniform rates
Gamma Parameter=Not Applicable
Pattern among Lineages=Same (Homogeneous)
Data Subset to Use=====================
Gaps/Missing Data Treatment=Pairwise deletion
Site Coverage Cutoff (%)=Not Applicable
